services:
  backend:
    build:
      context: ./smoked-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      postgres:
          condition: service_healthy
      redis:
          condition: service_started
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=arthur
      - DB_PASSWORD=hondadio
      - DB_NAME=meatdb
      - PORT=3000
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - JWT_SECRET=amfkdhfneigjtnfkgmdlsvmutskgsjrg
    networks:
      - app-network
    restart: unless-stopped
  
  frontend:
    build:
      context: ./smoked-frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: arthur
      POSTGRES_PASSWORD: hondadio
      POSTGRES_DB: meatdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arthur -d meatdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  pgdata:
  redis_data:

networks:
  app-network:
    driver: bridge